export const INCREASE='INCREASE'
export const DECREASE='DECREASE'
export const REMOVE='REMOVE'
export const LOADING='LOADING'
export const DISPLAY_ITEMS='DISPLAY_ITEMS'
export const CLEAR_CART='CLEAR_CART'